/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * This is an example opeartion to show how security is applied to the call.
   * 
   * Expected answers:
   *   code 200 :  (OK)
   */
  def exampleGet(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/wbmccool01/BSD/1.0.0", "/example", "application/json")
      .withSuccessResponse[Unit](200)
        /**
   * This operation shows how to override the global security defined above, as we want to open it up for all users.
   * 
   * Expected answers:
   *   code 200 :  (OK)
   */
  def pingGet(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/wbmccool01/BSD/1.0.0", "/ping", "application/json")
      .withSuccessResponse[Unit](200)
      

}

